name: Metrics
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # Optional: Run workflow manually
  workflow_dispatch:
  # Optional: Run workflow when pushing on master/main
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          filename: metrics.plugin.leetcode.svg
          base: ""
          plugin_leetcode_user: typewriter404
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.languages.indepth.svg
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
